# See https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "AI Room Cleaner"
version: "1.0.2"
slug: "ai_room_cleaner"
description: "Uses AI to analyze room cleanliness and create a to-do list."
arch:
  - "aarch64"
  - "amd64"
  - "armhf"
  - "armv7"
  - "i386"
init: false
map:
  - "config:rw"
options:
  camera_entity_id: "camera.your_camera"
  ai_provider: "Google Gemini"
  recheck_interval_minutes: 60
  todo_list_name: "AI Room Cleaner"
schema:
  camera_entity_id: "str"
  ai_provider: "list(Google Gemini|OpenAI)"
  api_key: "password"
  prompt: "str?"
  recheck_interval_minutes: "int(1,1440)"
  todo_list_name: "str"