# See https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "AI Room Cleaner"
version: "1.0.2"
slug: "ai_room_cleaner"
description: "Uses AI to analyze room cleanliness and create a to-do list."
homeassistant_api: true
arch:
  - "aarch64"
  - "amd64"
  - "armhf"
  - "armv7"
  - "i386"
init: false
map:
  - "config:rw"
options:
  log_level: "INFO"
  ai_provider: "openai"
  openai_api_key: ""
  openai_model: "gpt-4-vision-preview"
  google_api_key: ""
  google_model: "gemini-pro-vision"
  ai_prompt: >-
    Analyze the image of the room and identify any items that are out of place or contribute to messiness.
    Based on your analysis, create a concise to-do list for cleaning the room.
    Each item on the list should be a clear, actionable task.
  camera_entity_id: "camera.your_camera"
  todo_list_entity_id: "todo.ai_room_cleaner"
schema:
  log_level: "match(^(CRITICAL|ERROR|WARNING|INFO|DEBUG)$)"
  ai_provider: "list(openai|google_gemini)"
  openai_api_key: "password"
  openai_model: "str"
  google_api_key: "password"
  google_model: "str"
  ai_prompt: "str"
  camera_entity_id: "str"
  todo_list_entity_id: "str"
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12-slim"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.12-slim"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.12-slim"
args:
  BUILD_DATE: "$(date +%s)"